### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by akai1831** [lomholdt/arp#10]
Hi,

Thanks to the add-on extension you developed, it's really useful for us in Dashboard, however, We have a request, an option to add more than 1 Auto Start URL so that it'll open our required pages when Chrome startup. Hoping for your kind consideration. Thanks!

**Comment by krmarshall87** [comment]
I would agree that this feature would be great to have.  I have certain webpages load automatically on startup of the machine; now if I could get ARP to load on even a default frequency, that would be great!  Thanks!

**Comment by krmarshall87** [comment]
This feature may be better if the URL is monitored for the regex string inputted in the "Auto Start URL" field.  That way any number of pages could be opened, ARP identifies them as pages to be refreshed, and nothing is needed by the user.  This would be extremely helpful to me.  All my URLS are in the same domain, so no problem there; other users can use more advanced regex strings to have multiple domains/pages be refreshed.  Thanks!

**Comment by akai1831** [comment]
Very Outdated Add-on
