### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by przemo20** [lomholdt/arp#14]
Hi! I couldn't find another way to contact you, so I'm writing here. There should be "Default target text (or regex)" instead of "Deafault target text (or regex)" ( See screenshot below ).

![image](https://cloud.githubusercontent.com/assets/22180480/18527365/bffafe60-7ac4-11e6-8267-97a8423b435f.png)

**Comment by lomholdt** [comment]
I have fixed the spelling. Will upload the new version to the Chrome Web Store soon :)
