### ISSUE TITLE
Please add bigger time intervals

### ISSUE THREAD

**Issue by sciamannikoo** [lomholdt/arp#3]
I have a page which changes every few hours.

ARP only allows intervals up to 15 minutes, or a custom value in seconds: sure, I can just type 86400 seconds if i want a refresh of 12 hours, but I think it might be better if he time unit could be changed into a dropdown with seconds, minutes and hours options.

Thanks.

**Comment by lomholdt** [comment]
Hey there. I added this functionality, I will be updating the Chrome store in a minute, so you should be able to see it. Let me know if it works for you.

**Comment by sciamannikoo** [comment]
Thanks!
